Repository Flowpack/media-ui, pull requests merged in 2024-11, with the labels that each got.

#249 FEATURE: Protect referenced asset collections from being deleted
  Classes/GraphQL/Resolver/Type/AssetCollectionResolver.php
  Classes/GraphQL/Resolver/Type/MutationResolver.php
  Resources/Private/GraphQL/schema.root.graphql
  Resources/Private/JavaScript/asset-collections/src/components/DeleteButton.tsx
  Resources/Private/JavaScript/asset-collections/src/fragments/assetCollection.ts
  Resources/Private/JavaScript/asset-collections/typings/AssetCollection.ts
  Resources/Private/JavaScript/dev-server/src/fixtures/index.ts
  Resources/Private/JavaScript/dev-server/src/server.ts
  Resources/Private/JavaScript/media-module/package.json
  phpstan.neon
  yarn.lock
Labels: Feature

#251 FEATURE: Auto assign new assets to default collection and prevent removing last collection depending on config
  Classes/GraphQL/Resolver/Type/MutationResolver.php
  Classes/GraphQL/Resolver/Type/QueryResolver.php
  Classes/Service/AssetCollectionService.php
  Resources/Private/GraphQL/schema.root.graphql
  Resources/Private/JavaScript/core/src/hooks/useConfigQuery.ts
  Resources/Private/JavaScript/core/src/queries/config.ts
  Resources/Private/JavaScript/dev-server/src/server.ts
  Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/CollectionSelectBox.tsx
  Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/ParentCollectionSelectBox.tsx
Labels: Bug, Feature

#252 TASK: Upgrade to testcafe to version 3.6.2
  package.json
  yarn.lock
Labels: Enhancement

#242 FEATURE: Use custom transformer for flow exceptions
  Classes/GraphQL/Resolver/Type/MutationResolver.php
  Classes/Transform/FlowErrorTransform.php
  Configuration/Settings.GraphQL.yaml
  Resources/Private/JavaScript/asset-collections/src/components/CreateAssetCollectionDialog.tsx
  Resources/Private/JavaScript/asset-collections/src/components/DeleteButton.tsx
  Resources/Private/JavaScript/asset-tags/src/components/CreateTagDialog.tsx
  Resources/Private/JavaScript/asset-upload/src/components/Dialogs/NewAssetDialog.tsx
  Resources/Private/JavaScript/media-module/src/components/Main/AssetActions.tsx
  Resources/Private/JavaScript/media-module/src/core/CreateErrorHandler.ts
  Resources/Private/Translations/de/Main.xlf
  Resources/Private/Translations/en/Main.xlf
Labels: Feature, hacktoberfest-accepted

#241 FEATURE: Adds validation for create tag dialog
  Resources/Private/JavaScript/asset-collections/src/components/AddTagButton.tsx
  Resources/Private/JavaScript/asset-tags/src/components/CreateTagDialog.tsx
  Resources/Private/JavaScript/asset-tags/src/state/createTagDialogState.ts
  Resources/Private/JavaScript/media-module/tests/tags.ts
  Resources/Private/Translations/de/Main.xlf
  Resources/Private/Translations/en/Main.xlf
Labels: Feature, hacktoberfest-accepted
